package mocks

import mock "github.com/stretchr/testify/mock"
import request "github.com/aws/aws-sdk-go/aws/request"
import sns "github.com/aws/aws-sdk-go/service/sns"
import snsiface "github.com/aws/aws-sdk-go/service/sns/snsiface"

// SNSAPI is an autogenerated mock type for the SNSAPI type
type SNSAPI struct {
	mock.Mock
}

// AddPermission provides a mock function with given fields: _a0
func (_m *SNSAPI) AddPermission(_a0 *sns.AddPermissionInput) (*sns.AddPermissionOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.AddPermissionOutput
	if rf, ok := ret.Get(0).(func(*sns.AddPermissionInput) *sns.AddPermissionOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.AddPermissionOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.AddPermissionInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AddPermissionRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) AddPermissionRequest(_a0 *sns.AddPermissionInput) (*request.Request, *sns.AddPermissionOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.AddPermissionInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.AddPermissionOutput
	if rf, ok := ret.Get(1).(func(*sns.AddPermissionInput) *sns.AddPermissionOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.AddPermissionOutput)
		}
	}

	return r0, r1
}

// CheckIfPhoneNumberIsOptedOut provides a mock function with given fields: _a0
func (_m *SNSAPI) CheckIfPhoneNumberIsOptedOut(_a0 *sns.CheckIfPhoneNumberIsOptedOutInput) (*sns.CheckIfPhoneNumberIsOptedOutOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.CheckIfPhoneNumberIsOptedOutOutput
	if rf, ok := ret.Get(0).(func(*sns.CheckIfPhoneNumberIsOptedOutInput) *sns.CheckIfPhoneNumberIsOptedOutOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.CheckIfPhoneNumberIsOptedOutOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.CheckIfPhoneNumberIsOptedOutInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckIfPhoneNumberIsOptedOutRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) CheckIfPhoneNumberIsOptedOutRequest(_a0 *sns.CheckIfPhoneNumberIsOptedOutInput) (*request.Request, *sns.CheckIfPhoneNumberIsOptedOutOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.CheckIfPhoneNumberIsOptedOutInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.CheckIfPhoneNumberIsOptedOutOutput
	if rf, ok := ret.Get(1).(func(*sns.CheckIfPhoneNumberIsOptedOutInput) *sns.CheckIfPhoneNumberIsOptedOutOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.CheckIfPhoneNumberIsOptedOutOutput)
		}
	}

	return r0, r1
}

// ConfirmSubscription provides a mock function with given fields: _a0
func (_m *SNSAPI) ConfirmSubscription(_a0 *sns.ConfirmSubscriptionInput) (*sns.ConfirmSubscriptionOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.ConfirmSubscriptionOutput
	if rf, ok := ret.Get(0).(func(*sns.ConfirmSubscriptionInput) *sns.ConfirmSubscriptionOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.ConfirmSubscriptionOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.ConfirmSubscriptionInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfirmSubscriptionRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) ConfirmSubscriptionRequest(_a0 *sns.ConfirmSubscriptionInput) (*request.Request, *sns.ConfirmSubscriptionOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.ConfirmSubscriptionInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.ConfirmSubscriptionOutput
	if rf, ok := ret.Get(1).(func(*sns.ConfirmSubscriptionInput) *sns.ConfirmSubscriptionOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.ConfirmSubscriptionOutput)
		}
	}

	return r0, r1
}

// CreatePlatformApplication provides a mock function with given fields: _a0
func (_m *SNSAPI) CreatePlatformApplication(_a0 *sns.CreatePlatformApplicationInput) (*sns.CreatePlatformApplicationOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.CreatePlatformApplicationOutput
	if rf, ok := ret.Get(0).(func(*sns.CreatePlatformApplicationInput) *sns.CreatePlatformApplicationOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.CreatePlatformApplicationOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.CreatePlatformApplicationInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreatePlatformApplicationRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) CreatePlatformApplicationRequest(_a0 *sns.CreatePlatformApplicationInput) (*request.Request, *sns.CreatePlatformApplicationOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.CreatePlatformApplicationInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.CreatePlatformApplicationOutput
	if rf, ok := ret.Get(1).(func(*sns.CreatePlatformApplicationInput) *sns.CreatePlatformApplicationOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.CreatePlatformApplicationOutput)
		}
	}

	return r0, r1
}

// CreatePlatformEndpoint provides a mock function with given fields: _a0
func (_m *SNSAPI) CreatePlatformEndpoint(_a0 *sns.CreatePlatformEndpointInput) (*sns.CreatePlatformEndpointOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.CreatePlatformEndpointOutput
	if rf, ok := ret.Get(0).(func(*sns.CreatePlatformEndpointInput) *sns.CreatePlatformEndpointOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.CreatePlatformEndpointOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.CreatePlatformEndpointInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreatePlatformEndpointRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) CreatePlatformEndpointRequest(_a0 *sns.CreatePlatformEndpointInput) (*request.Request, *sns.CreatePlatformEndpointOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.CreatePlatformEndpointInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.CreatePlatformEndpointOutput
	if rf, ok := ret.Get(1).(func(*sns.CreatePlatformEndpointInput) *sns.CreatePlatformEndpointOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.CreatePlatformEndpointOutput)
		}
	}

	return r0, r1
}

// CreateTopic provides a mock function with given fields: _a0
func (_m *SNSAPI) CreateTopic(_a0 *sns.CreateTopicInput) (*sns.CreateTopicOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.CreateTopicOutput
	if rf, ok := ret.Get(0).(func(*sns.CreateTopicInput) *sns.CreateTopicOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.CreateTopicOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.CreateTopicInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateTopicRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) CreateTopicRequest(_a0 *sns.CreateTopicInput) (*request.Request, *sns.CreateTopicOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.CreateTopicInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.CreateTopicOutput
	if rf, ok := ret.Get(1).(func(*sns.CreateTopicInput) *sns.CreateTopicOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.CreateTopicOutput)
		}
	}

	return r0, r1
}

// DeleteEndpoint provides a mock function with given fields: _a0
func (_m *SNSAPI) DeleteEndpoint(_a0 *sns.DeleteEndpointInput) (*sns.DeleteEndpointOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.DeleteEndpointOutput
	if rf, ok := ret.Get(0).(func(*sns.DeleteEndpointInput) *sns.DeleteEndpointOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.DeleteEndpointOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.DeleteEndpointInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteEndpointRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) DeleteEndpointRequest(_a0 *sns.DeleteEndpointInput) (*request.Request, *sns.DeleteEndpointOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.DeleteEndpointInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.DeleteEndpointOutput
	if rf, ok := ret.Get(1).(func(*sns.DeleteEndpointInput) *sns.DeleteEndpointOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.DeleteEndpointOutput)
		}
	}

	return r0, r1
}

// DeletePlatformApplication provides a mock function with given fields: _a0
func (_m *SNSAPI) DeletePlatformApplication(_a0 *sns.DeletePlatformApplicationInput) (*sns.DeletePlatformApplicationOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.DeletePlatformApplicationOutput
	if rf, ok := ret.Get(0).(func(*sns.DeletePlatformApplicationInput) *sns.DeletePlatformApplicationOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.DeletePlatformApplicationOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.DeletePlatformApplicationInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeletePlatformApplicationRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) DeletePlatformApplicationRequest(_a0 *sns.DeletePlatformApplicationInput) (*request.Request, *sns.DeletePlatformApplicationOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.DeletePlatformApplicationInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.DeletePlatformApplicationOutput
	if rf, ok := ret.Get(1).(func(*sns.DeletePlatformApplicationInput) *sns.DeletePlatformApplicationOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.DeletePlatformApplicationOutput)
		}
	}

	return r0, r1
}

// DeleteTopic provides a mock function with given fields: _a0
func (_m *SNSAPI) DeleteTopic(_a0 *sns.DeleteTopicInput) (*sns.DeleteTopicOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.DeleteTopicOutput
	if rf, ok := ret.Get(0).(func(*sns.DeleteTopicInput) *sns.DeleteTopicOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.DeleteTopicOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.DeleteTopicInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTopicRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) DeleteTopicRequest(_a0 *sns.DeleteTopicInput) (*request.Request, *sns.DeleteTopicOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.DeleteTopicInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.DeleteTopicOutput
	if rf, ok := ret.Get(1).(func(*sns.DeleteTopicInput) *sns.DeleteTopicOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.DeleteTopicOutput)
		}
	}

	return r0, r1
}

// GetEndpointAttributes provides a mock function with given fields: _a0
func (_m *SNSAPI) GetEndpointAttributes(_a0 *sns.GetEndpointAttributesInput) (*sns.GetEndpointAttributesOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.GetEndpointAttributesOutput
	if rf, ok := ret.Get(0).(func(*sns.GetEndpointAttributesInput) *sns.GetEndpointAttributesOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.GetEndpointAttributesOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.GetEndpointAttributesInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEndpointAttributesRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) GetEndpointAttributesRequest(_a0 *sns.GetEndpointAttributesInput) (*request.Request, *sns.GetEndpointAttributesOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.GetEndpointAttributesInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.GetEndpointAttributesOutput
	if rf, ok := ret.Get(1).(func(*sns.GetEndpointAttributesInput) *sns.GetEndpointAttributesOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.GetEndpointAttributesOutput)
		}
	}

	return r0, r1
}

// GetPlatformApplicationAttributes provides a mock function with given fields: _a0
func (_m *SNSAPI) GetPlatformApplicationAttributes(_a0 *sns.GetPlatformApplicationAttributesInput) (*sns.GetPlatformApplicationAttributesOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.GetPlatformApplicationAttributesOutput
	if rf, ok := ret.Get(0).(func(*sns.GetPlatformApplicationAttributesInput) *sns.GetPlatformApplicationAttributesOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.GetPlatformApplicationAttributesOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.GetPlatformApplicationAttributesInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlatformApplicationAttributesRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) GetPlatformApplicationAttributesRequest(_a0 *sns.GetPlatformApplicationAttributesInput) (*request.Request, *sns.GetPlatformApplicationAttributesOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.GetPlatformApplicationAttributesInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.GetPlatformApplicationAttributesOutput
	if rf, ok := ret.Get(1).(func(*sns.GetPlatformApplicationAttributesInput) *sns.GetPlatformApplicationAttributesOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.GetPlatformApplicationAttributesOutput)
		}
	}

	return r0, r1
}

// GetSMSAttributes provides a mock function with given fields: _a0
func (_m *SNSAPI) GetSMSAttributes(_a0 *sns.GetSMSAttributesInput) (*sns.GetSMSAttributesOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.GetSMSAttributesOutput
	if rf, ok := ret.Get(0).(func(*sns.GetSMSAttributesInput) *sns.GetSMSAttributesOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.GetSMSAttributesOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.GetSMSAttributesInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSMSAttributesRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) GetSMSAttributesRequest(_a0 *sns.GetSMSAttributesInput) (*request.Request, *sns.GetSMSAttributesOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.GetSMSAttributesInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.GetSMSAttributesOutput
	if rf, ok := ret.Get(1).(func(*sns.GetSMSAttributesInput) *sns.GetSMSAttributesOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.GetSMSAttributesOutput)
		}
	}

	return r0, r1
}

// GetSubscriptionAttributes provides a mock function with given fields: _a0
func (_m *SNSAPI) GetSubscriptionAttributes(_a0 *sns.GetSubscriptionAttributesInput) (*sns.GetSubscriptionAttributesOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.GetSubscriptionAttributesOutput
	if rf, ok := ret.Get(0).(func(*sns.GetSubscriptionAttributesInput) *sns.GetSubscriptionAttributesOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.GetSubscriptionAttributesOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.GetSubscriptionAttributesInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSubscriptionAttributesRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) GetSubscriptionAttributesRequest(_a0 *sns.GetSubscriptionAttributesInput) (*request.Request, *sns.GetSubscriptionAttributesOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.GetSubscriptionAttributesInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.GetSubscriptionAttributesOutput
	if rf, ok := ret.Get(1).(func(*sns.GetSubscriptionAttributesInput) *sns.GetSubscriptionAttributesOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.GetSubscriptionAttributesOutput)
		}
	}

	return r0, r1
}

// GetTopicAttributes provides a mock function with given fields: _a0
func (_m *SNSAPI) GetTopicAttributes(_a0 *sns.GetTopicAttributesInput) (*sns.GetTopicAttributesOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.GetTopicAttributesOutput
	if rf, ok := ret.Get(0).(func(*sns.GetTopicAttributesInput) *sns.GetTopicAttributesOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.GetTopicAttributesOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.GetTopicAttributesInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTopicAttributesRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) GetTopicAttributesRequest(_a0 *sns.GetTopicAttributesInput) (*request.Request, *sns.GetTopicAttributesOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.GetTopicAttributesInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.GetTopicAttributesOutput
	if rf, ok := ret.Get(1).(func(*sns.GetTopicAttributesInput) *sns.GetTopicAttributesOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.GetTopicAttributesOutput)
		}
	}

	return r0, r1
}

// ListEndpointsByPlatformApplication provides a mock function with given fields: _a0
func (_m *SNSAPI) ListEndpointsByPlatformApplication(_a0 *sns.ListEndpointsByPlatformApplicationInput) (*sns.ListEndpointsByPlatformApplicationOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.ListEndpointsByPlatformApplicationOutput
	if rf, ok := ret.Get(0).(func(*sns.ListEndpointsByPlatformApplicationInput) *sns.ListEndpointsByPlatformApplicationOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.ListEndpointsByPlatformApplicationOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.ListEndpointsByPlatformApplicationInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListEndpointsByPlatformApplicationPages provides a mock function with given fields: _a0, _a1
func (_m *SNSAPI) ListEndpointsByPlatformApplicationPages(_a0 *sns.ListEndpointsByPlatformApplicationInput, _a1 func(*sns.ListEndpointsByPlatformApplicationOutput, bool) bool) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*sns.ListEndpointsByPlatformApplicationInput, func(*sns.ListEndpointsByPlatformApplicationOutput, bool) bool) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListEndpointsByPlatformApplicationRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) ListEndpointsByPlatformApplicationRequest(_a0 *sns.ListEndpointsByPlatformApplicationInput) (*request.Request, *sns.ListEndpointsByPlatformApplicationOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.ListEndpointsByPlatformApplicationInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.ListEndpointsByPlatformApplicationOutput
	if rf, ok := ret.Get(1).(func(*sns.ListEndpointsByPlatformApplicationInput) *sns.ListEndpointsByPlatformApplicationOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.ListEndpointsByPlatformApplicationOutput)
		}
	}

	return r0, r1
}

// ListPhoneNumbersOptedOut provides a mock function with given fields: _a0
func (_m *SNSAPI) ListPhoneNumbersOptedOut(_a0 *sns.ListPhoneNumbersOptedOutInput) (*sns.ListPhoneNumbersOptedOutOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.ListPhoneNumbersOptedOutOutput
	if rf, ok := ret.Get(0).(func(*sns.ListPhoneNumbersOptedOutInput) *sns.ListPhoneNumbersOptedOutOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.ListPhoneNumbersOptedOutOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.ListPhoneNumbersOptedOutInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPhoneNumbersOptedOutRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) ListPhoneNumbersOptedOutRequest(_a0 *sns.ListPhoneNumbersOptedOutInput) (*request.Request, *sns.ListPhoneNumbersOptedOutOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.ListPhoneNumbersOptedOutInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.ListPhoneNumbersOptedOutOutput
	if rf, ok := ret.Get(1).(func(*sns.ListPhoneNumbersOptedOutInput) *sns.ListPhoneNumbersOptedOutOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.ListPhoneNumbersOptedOutOutput)
		}
	}

	return r0, r1
}

// ListPlatformApplications provides a mock function with given fields: _a0
func (_m *SNSAPI) ListPlatformApplications(_a0 *sns.ListPlatformApplicationsInput) (*sns.ListPlatformApplicationsOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.ListPlatformApplicationsOutput
	if rf, ok := ret.Get(0).(func(*sns.ListPlatformApplicationsInput) *sns.ListPlatformApplicationsOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.ListPlatformApplicationsOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.ListPlatformApplicationsInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPlatformApplicationsPages provides a mock function with given fields: _a0, _a1
func (_m *SNSAPI) ListPlatformApplicationsPages(_a0 *sns.ListPlatformApplicationsInput, _a1 func(*sns.ListPlatformApplicationsOutput, bool) bool) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*sns.ListPlatformApplicationsInput, func(*sns.ListPlatformApplicationsOutput, bool) bool) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListPlatformApplicationsRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) ListPlatformApplicationsRequest(_a0 *sns.ListPlatformApplicationsInput) (*request.Request, *sns.ListPlatformApplicationsOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.ListPlatformApplicationsInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.ListPlatformApplicationsOutput
	if rf, ok := ret.Get(1).(func(*sns.ListPlatformApplicationsInput) *sns.ListPlatformApplicationsOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.ListPlatformApplicationsOutput)
		}
	}

	return r0, r1
}

// ListSubscriptions provides a mock function with given fields: _a0
func (_m *SNSAPI) ListSubscriptions(_a0 *sns.ListSubscriptionsInput) (*sns.ListSubscriptionsOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.ListSubscriptionsOutput
	if rf, ok := ret.Get(0).(func(*sns.ListSubscriptionsInput) *sns.ListSubscriptionsOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.ListSubscriptionsOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.ListSubscriptionsInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSubscriptionsByTopic provides a mock function with given fields: _a0
func (_m *SNSAPI) ListSubscriptionsByTopic(_a0 *sns.ListSubscriptionsByTopicInput) (*sns.ListSubscriptionsByTopicOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.ListSubscriptionsByTopicOutput
	if rf, ok := ret.Get(0).(func(*sns.ListSubscriptionsByTopicInput) *sns.ListSubscriptionsByTopicOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.ListSubscriptionsByTopicOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.ListSubscriptionsByTopicInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSubscriptionsByTopicPages provides a mock function with given fields: _a0, _a1
func (_m *SNSAPI) ListSubscriptionsByTopicPages(_a0 *sns.ListSubscriptionsByTopicInput, _a1 func(*sns.ListSubscriptionsByTopicOutput, bool) bool) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*sns.ListSubscriptionsByTopicInput, func(*sns.ListSubscriptionsByTopicOutput, bool) bool) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListSubscriptionsByTopicRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) ListSubscriptionsByTopicRequest(_a0 *sns.ListSubscriptionsByTopicInput) (*request.Request, *sns.ListSubscriptionsByTopicOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.ListSubscriptionsByTopicInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.ListSubscriptionsByTopicOutput
	if rf, ok := ret.Get(1).(func(*sns.ListSubscriptionsByTopicInput) *sns.ListSubscriptionsByTopicOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.ListSubscriptionsByTopicOutput)
		}
	}

	return r0, r1
}

// ListSubscriptionsPages provides a mock function with given fields: _a0, _a1
func (_m *SNSAPI) ListSubscriptionsPages(_a0 *sns.ListSubscriptionsInput, _a1 func(*sns.ListSubscriptionsOutput, bool) bool) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*sns.ListSubscriptionsInput, func(*sns.ListSubscriptionsOutput, bool) bool) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListSubscriptionsRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) ListSubscriptionsRequest(_a0 *sns.ListSubscriptionsInput) (*request.Request, *sns.ListSubscriptionsOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.ListSubscriptionsInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.ListSubscriptionsOutput
	if rf, ok := ret.Get(1).(func(*sns.ListSubscriptionsInput) *sns.ListSubscriptionsOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.ListSubscriptionsOutput)
		}
	}

	return r0, r1
}

// ListTopics provides a mock function with given fields: _a0
func (_m *SNSAPI) ListTopics(_a0 *sns.ListTopicsInput) (*sns.ListTopicsOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.ListTopicsOutput
	if rf, ok := ret.Get(0).(func(*sns.ListTopicsInput) *sns.ListTopicsOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.ListTopicsOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.ListTopicsInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTopicsPages provides a mock function with given fields: _a0, _a1
func (_m *SNSAPI) ListTopicsPages(_a0 *sns.ListTopicsInput, _a1 func(*sns.ListTopicsOutput, bool) bool) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*sns.ListTopicsInput, func(*sns.ListTopicsOutput, bool) bool) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListTopicsRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) ListTopicsRequest(_a0 *sns.ListTopicsInput) (*request.Request, *sns.ListTopicsOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.ListTopicsInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.ListTopicsOutput
	if rf, ok := ret.Get(1).(func(*sns.ListTopicsInput) *sns.ListTopicsOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.ListTopicsOutput)
		}
	}

	return r0, r1
}

// OptInPhoneNumber provides a mock function with given fields: _a0
func (_m *SNSAPI) OptInPhoneNumber(_a0 *sns.OptInPhoneNumberInput) (*sns.OptInPhoneNumberOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.OptInPhoneNumberOutput
	if rf, ok := ret.Get(0).(func(*sns.OptInPhoneNumberInput) *sns.OptInPhoneNumberOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.OptInPhoneNumberOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.OptInPhoneNumberInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OptInPhoneNumberRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) OptInPhoneNumberRequest(_a0 *sns.OptInPhoneNumberInput) (*request.Request, *sns.OptInPhoneNumberOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.OptInPhoneNumberInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.OptInPhoneNumberOutput
	if rf, ok := ret.Get(1).(func(*sns.OptInPhoneNumberInput) *sns.OptInPhoneNumberOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.OptInPhoneNumberOutput)
		}
	}

	return r0, r1
}

// Publish provides a mock function with given fields: _a0
func (_m *SNSAPI) Publish(_a0 *sns.PublishInput) (*sns.PublishOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.PublishOutput
	if rf, ok := ret.Get(0).(func(*sns.PublishInput) *sns.PublishOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.PublishOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.PublishInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PublishRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) PublishRequest(_a0 *sns.PublishInput) (*request.Request, *sns.PublishOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.PublishInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.PublishOutput
	if rf, ok := ret.Get(1).(func(*sns.PublishInput) *sns.PublishOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.PublishOutput)
		}
	}

	return r0, r1
}

// RemovePermission provides a mock function with given fields: _a0
func (_m *SNSAPI) RemovePermission(_a0 *sns.RemovePermissionInput) (*sns.RemovePermissionOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.RemovePermissionOutput
	if rf, ok := ret.Get(0).(func(*sns.RemovePermissionInput) *sns.RemovePermissionOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.RemovePermissionOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.RemovePermissionInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemovePermissionRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) RemovePermissionRequest(_a0 *sns.RemovePermissionInput) (*request.Request, *sns.RemovePermissionOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.RemovePermissionInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.RemovePermissionOutput
	if rf, ok := ret.Get(1).(func(*sns.RemovePermissionInput) *sns.RemovePermissionOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.RemovePermissionOutput)
		}
	}

	return r0, r1
}

// SetEndpointAttributes provides a mock function with given fields: _a0
func (_m *SNSAPI) SetEndpointAttributes(_a0 *sns.SetEndpointAttributesInput) (*sns.SetEndpointAttributesOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.SetEndpointAttributesOutput
	if rf, ok := ret.Get(0).(func(*sns.SetEndpointAttributesInput) *sns.SetEndpointAttributesOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.SetEndpointAttributesOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.SetEndpointAttributesInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetEndpointAttributesRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) SetEndpointAttributesRequest(_a0 *sns.SetEndpointAttributesInput) (*request.Request, *sns.SetEndpointAttributesOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.SetEndpointAttributesInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.SetEndpointAttributesOutput
	if rf, ok := ret.Get(1).(func(*sns.SetEndpointAttributesInput) *sns.SetEndpointAttributesOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.SetEndpointAttributesOutput)
		}
	}

	return r0, r1
}

// SetPlatformApplicationAttributes provides a mock function with given fields: _a0
func (_m *SNSAPI) SetPlatformApplicationAttributes(_a0 *sns.SetPlatformApplicationAttributesInput) (*sns.SetPlatformApplicationAttributesOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.SetPlatformApplicationAttributesOutput
	if rf, ok := ret.Get(0).(func(*sns.SetPlatformApplicationAttributesInput) *sns.SetPlatformApplicationAttributesOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.SetPlatformApplicationAttributesOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.SetPlatformApplicationAttributesInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetPlatformApplicationAttributesRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) SetPlatformApplicationAttributesRequest(_a0 *sns.SetPlatformApplicationAttributesInput) (*request.Request, *sns.SetPlatformApplicationAttributesOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.SetPlatformApplicationAttributesInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.SetPlatformApplicationAttributesOutput
	if rf, ok := ret.Get(1).(func(*sns.SetPlatformApplicationAttributesInput) *sns.SetPlatformApplicationAttributesOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.SetPlatformApplicationAttributesOutput)
		}
	}

	return r0, r1
}

// SetSMSAttributes provides a mock function with given fields: _a0
func (_m *SNSAPI) SetSMSAttributes(_a0 *sns.SetSMSAttributesInput) (*sns.SetSMSAttributesOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.SetSMSAttributesOutput
	if rf, ok := ret.Get(0).(func(*sns.SetSMSAttributesInput) *sns.SetSMSAttributesOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.SetSMSAttributesOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.SetSMSAttributesInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetSMSAttributesRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) SetSMSAttributesRequest(_a0 *sns.SetSMSAttributesInput) (*request.Request, *sns.SetSMSAttributesOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.SetSMSAttributesInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.SetSMSAttributesOutput
	if rf, ok := ret.Get(1).(func(*sns.SetSMSAttributesInput) *sns.SetSMSAttributesOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.SetSMSAttributesOutput)
		}
	}

	return r0, r1
}

// SetSubscriptionAttributes provides a mock function with given fields: _a0
func (_m *SNSAPI) SetSubscriptionAttributes(_a0 *sns.SetSubscriptionAttributesInput) (*sns.SetSubscriptionAttributesOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.SetSubscriptionAttributesOutput
	if rf, ok := ret.Get(0).(func(*sns.SetSubscriptionAttributesInput) *sns.SetSubscriptionAttributesOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.SetSubscriptionAttributesOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.SetSubscriptionAttributesInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetSubscriptionAttributesRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) SetSubscriptionAttributesRequest(_a0 *sns.SetSubscriptionAttributesInput) (*request.Request, *sns.SetSubscriptionAttributesOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.SetSubscriptionAttributesInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.SetSubscriptionAttributesOutput
	if rf, ok := ret.Get(1).(func(*sns.SetSubscriptionAttributesInput) *sns.SetSubscriptionAttributesOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.SetSubscriptionAttributesOutput)
		}
	}

	return r0, r1
}

// SetTopicAttributes provides a mock function with given fields: _a0
func (_m *SNSAPI) SetTopicAttributes(_a0 *sns.SetTopicAttributesInput) (*sns.SetTopicAttributesOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.SetTopicAttributesOutput
	if rf, ok := ret.Get(0).(func(*sns.SetTopicAttributesInput) *sns.SetTopicAttributesOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.SetTopicAttributesOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.SetTopicAttributesInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetTopicAttributesRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) SetTopicAttributesRequest(_a0 *sns.SetTopicAttributesInput) (*request.Request, *sns.SetTopicAttributesOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.SetTopicAttributesInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.SetTopicAttributesOutput
	if rf, ok := ret.Get(1).(func(*sns.SetTopicAttributesInput) *sns.SetTopicAttributesOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.SetTopicAttributesOutput)
		}
	}

	return r0, r1
}

// Subscribe provides a mock function with given fields: _a0
func (_m *SNSAPI) Subscribe(_a0 *sns.SubscribeInput) (*sns.SubscribeOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.SubscribeOutput
	if rf, ok := ret.Get(0).(func(*sns.SubscribeInput) *sns.SubscribeOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.SubscribeOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.SubscribeInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubscribeRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) SubscribeRequest(_a0 *sns.SubscribeInput) (*request.Request, *sns.SubscribeOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.SubscribeInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.SubscribeOutput
	if rf, ok := ret.Get(1).(func(*sns.SubscribeInput) *sns.SubscribeOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.SubscribeOutput)
		}
	}

	return r0, r1
}

// Unsubscribe provides a mock function with given fields: _a0
func (_m *SNSAPI) Unsubscribe(_a0 *sns.UnsubscribeInput) (*sns.UnsubscribeOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sns.UnsubscribeOutput
	if rf, ok := ret.Get(0).(func(*sns.UnsubscribeInput) *sns.UnsubscribeOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.UnsubscribeOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sns.UnsubscribeInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnsubscribeRequest provides a mock function with given fields: _a0
func (_m *SNSAPI) UnsubscribeRequest(_a0 *sns.UnsubscribeInput) (*request.Request, *sns.UnsubscribeOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*sns.UnsubscribeInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *sns.UnsubscribeOutput
	if rf, ok := ret.Get(1).(func(*sns.UnsubscribeInput) *sns.UnsubscribeOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sns.UnsubscribeOutput)
		}
	}

	return r0, r1
}

var _ snsiface.SNSAPI = (*SNSAPI)(nil)
